name: rattle
description: Rattle Data Science Next Generation
publish_to: 'none'
version: 6.4.11+181

environment:
  sdk: '>=3.0.5 <4.0.0'

# To automatically upgrade package dependencies:
#
# `flutter pub upgrade --major-versions`.
#
# To see which dependencies have newer versions available:
#
# `flutter pub outdated`

dependencies:
  flutter:
    sdk: flutter

  # flutter_pty: ^0.4.0
  #
  # The following git source fixes the problem with R not being able
  # to access the user's installed packages. It is a PR on the
  # original package
  #
  # https://github.com/TerminalStudio/flutter_pty/pull/15
  #
  # However this then does not compile for Linux
  #
  # /home/gjw/git/github/gjwgit/rattleng/linux/flutter/ephemeral/.plugin_symlinks/flutter_pty/src/flutter_pty_unix.c:114:5:
  # error: call to undeclared function 'waitpid'; ISO C99 and later do
  # not support implicit function declarations
  # [-Wimplicit-function-declaration]
  #
  flutter_pty:
    git:
      url: https://github.com/Lutra-Fs/flutter_pty.git
      ref: main

  catppuccin_flutter: ^1.0.0
  file_picker: ^8.0.6
  flutter_markdown: ^0.7.1
  flutter_riverpod: ^2.4.4
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  intl: ^0.20.1
  markdown_tooltip: ^0.0.6
# markdown_tooltip:
#   path: markdown_tooltip
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.1.3
  pdf: ^3.11.1
  provider: ^6.0.5
  riverpod_annotation: ^2.2.1
  shared_preferences: ^2.3.3
  universal_io: ^2.2.2
  url_launcher: ^6.3.0
  window_manager: ^0.4.3
  xterm: ^4.0.0
  git: ^2.3.0

  http: any
  yaml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  build_runner: ^2.4.6
  custom_lint: ^0.7.0
  dependency_validator: ^4.1.1
  flutter_gen: ^5.3.1
  flutter_launcher_icons: ^0.14.2

  # The `flutter_lints` package contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the
  # package is activated in the `analysis_options.yaml` file located
  # at the root of your package. See that file for information about
  # deactivating specific lint rules and activating additional ones.

  flutter_lints: ^5.0.0
  msix: ^3.16.2
  riverpod_generator: ^2.3.5

  # TODO 20240604 gjw FOR NOW REMOVE riverpod_lint AS IT HAS
  # DEPENDENCY CONFLICTS WITH dart_code_metrics.

  # riverpod_lint: ^2.3.2

  # The original `dart-code-metrics` is end of live and has migrated to
  # a paid service. This fork maintains it's compatibility with the
  # latest flutter.

  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev

dependency_overrides:
  collection: ^1.19.0  # Required for dart-code-metrics.

flutter:
  uses-material-design: true

  # Note the full image path is required for the resource: image use
  # in flutter_markdown.

  assets:
    - assets/data/audit.csv
    - assets/data/movies.csv
    - assets/data/protein.csv
    - assets/data/sherlock.txt
    - assets/data/weather.csv
    - assets/data/co-est2016-alldata.csv
    - assets/images/favicon_small.png
    - assets/icons/icon.png
    - assets/markdown/
    - assets/r/
    - assets/svg/

  # Use a fixed width Ubuntu font for the Log tab.

  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-R.ttf
      # Google font family https://fonts.google.com/
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    # - family: NotoSans
    #   fonts:
    #     - asset: assets/fonts/NotoSans-Regular.ttf
    #
    # A fullback font supporting unicode block characters used in skimr.
    - family: DejaVuSans
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Settings for creating .msix file, that can be installed in a windows
# machine This can be customized, see
# https://pub.dev/packages/msix/example for reference

msix_config:
  display_name: rattle
  msix_version: 1.0.0.0
  certificate_path: CERTIFICATE.pfx
  certificate_password: rattle1234
  execution_alias: rattle

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/icons/icon.png'
  windows:
    generate: true
    image_path: 'assets/icons/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icons/icon.png'
