name: rattle
version: 0.2.0
summary: Rattle Next Generation Data Science App
description: Rattle is the data scientists toolkit.

confinement: strict
base: core22
grade: stable

slots:
  dbus-rattle:
    interface: dbus
    bus: session
    name: com.togaware.rattle
    
apps:
  rattle:
    command: rattle
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
    - network
    slots:
      - dbus-rattle
parts:
  rattle:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application

plugs:
  r-executable:
    interface: system-files
    read:
      - /usr/bin/R
