name: Installer Bulder

on:
  push:
    branches:
      - dev

jobs:

  # This was used for testing different linux machines.
  
  # build-release-upload-ubuntu:
  #   if: contains(github.event.head_commit.message, 'bump version')
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Confirm the branch
  #       run: git status
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #         architecture: x64
  #         flutter-version: 3.22.2
  #     - run: flutter --version
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y ninja-build libgtk-3-dev
  #         sudo apt-get install -y clang cmake
  #     - name: Build package
  #       run: flutter build linux --release
  #     - name: Zip the bundle
  #       uses: thedoctor0/zip-release@master
  #       with:
  #         type: 'zip'
  #         filename: rattle-${{github.ref_name}}-ubuntu.zip
  #         directory: build/linux/x64/release/bundle
  #     - name: Upload the zip bundle to Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: rattle-ubuntu
  #         path: build/linux/x64/release/bundle/rattle-${{github.ref_name}}-ubuntu.zip
  #     - name: Ubuntu Release
  #       uses: softprops/action-gh-release@v2
  #       if: startsWith(github.ref, 'refs/tags/')
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         files: build/linux/x64/release/bundle/rattle-${{github.ref_name}}-ubuntu.zip

  # Originally I was building on Ubuntu 22.04 since my 24.04 version
  # would not run on Mint 21.3. Then moved even older to Ubuntu 20.04
  # to get it more widely available. Seems to work on 22.04 and
  # 24.04. Backwards the error was: "rattle:
  # /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found
  # (required by rattle)" On Ubuntu 20.04 the highest version of GLIBC
  # is GLIBC2.30.
  
  build-linux-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Confirm Branch
        run: git status

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          flutter-version: 3.24.1

      - name: Confirm Flutter Version
        run: flutter --version

      - name: Install OS Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y clang cmake

      - name: Install flutter project dependencies
        run: flutter pub get
        
      - name: Enable Linux Build
        run: flutter config --enable-linux-desktop

      - name: Build Artifact
        run: flutter build linux --release

      - name: Zip Bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{ github.ref_name }}-linux.zip
          directory: build/linux/x64/release/bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rattle-linux-zip
          path: build/linux/x64/release/bundle/rattle-${{ github.ref_name }}-linux.zip

########################################################################

  build-windows-inno:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: windows-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.1'

      - name: Install Project Dependencies
        run: flutter pub get

      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop

      - name: Build Artifact
        run: flutter build windows

      - name: Get Version from pubspec.yaml
        run: |
          $version = (Get-Content pubspec.yaml | Select-String '^version:[^^]*' | ForEach-Object { $_.ToString().Split(":")[1].Trim().Split("+")[0].Trim() })
          echo "APP_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installers/rattleng-windows.iss
          options: /O+

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rattle-windows-inno
          path: D:\a\rattleng\rattleng\installers\installers\rattle-0.0.0.exe

########################################################################

  build-windows-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Windows Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/rattle-${{github.ref_name}}-windows.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rattle-windows-zip
          path: build/windows/x64/runner/Release/rattle-${{github.ref_name}}-windows.zip

########################################################################

  build-macos-zip:
    if: contains(github.event.head_commit.message, 'bump version')
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.24.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - run: ls -laRsh
      - name: macOS Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/rattle-${{github.ref_name}}-macos.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rattle-macos-zip
          path: build/macos/Build/Products/Release/rattle-${{github.ref_name}}-macos.zip
