name: Lint Checks

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened, synchronize]


env:
  FLUTTER_MIN_VERSION: '3.22.0'

jobs:
  # BEGIN LINTING STAGE
  # format:
  #   if: contains(github.event.head_commit.message, 'cicd')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #     - uses: bluefireteam/melos-action@v3
  #     - run: melos run format-check

  # analyze:
  #   if: contains(github.event.head_commit.message, 'cicd')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: ${{env.FLUTTER_MIN_VERSION}}
  #     - uses: bluefireteam/melos-action@v3
  #     - name: "Analyze with lowest supported version"
  #       uses: invertase/github-action-dart-analyzer@v3
  #       with:
  #         fatal-infos: true

  # analyze-latest:
  #   if: contains(github.event.head_commit.message, 'cicd')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #     - uses: bluefireteam/melos-action@v3
  #     - name: "Analyze with latest stable"
  #       uses: invertase/github-action-dart-analyzer@v3
  #       with:
  #         fatal-infos: true

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g markdownlint-cli
      - run: markdownlint assets/markdown
        # -p .markdownlintignore -c .markdownlint.yaml

  dcm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: dcm analyze .
  # END LINTING STAGE

  # BEGIN TESTING STAGE
  # test:
  #   if: contains(github.event.head_commit.message, 'cicd')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         cache: true
  #     - uses: bluefireteam/melos-action@v3
  #     - name: Run tests
  #       run: melos test
  # END TESTING STAGE
