name: Lint Checks

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FLUTTER_VERSION: '3.24.3'

jobs:
  # BEGIN LINTING STAGE

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: flutter analyze --fatal-infos

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g markdownlint-cli
      - run: markdownlint assets/markdown
        # -p .markdownlintignore -c .markdownlint.yaml

  dcm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: dcm analyze lib
      # Total fail - run: dcm check-unused-code lib

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: sudo apt update
      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip libunwind-dev
      - run: flutter pub get
      - run: flutter build linux -v

# END LINTING STAGE

  # BEGIN TESTING STAGE
  # test:
  #   if: contains(github.event.head_commit.message, 'cicd')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         cache: true
  #     - uses: bluefireteam/melos-action@v3
  #     - name: Run tests
  #       run: melos test
  # END TESTING STAGE
