name: Integration Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        architecture: x64
        flutter-version: 3.24.1
  
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y clang cmake
    
    - name: Install X11 dependencies on MacOS
      if: runner.os == 'macOS'
      run: |
        brew --cask install xquartz

    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Run tests
      run: make qtest