name: Integration Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        architecture: x64
        flutter-version: 3.24.1
  
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    

    - name: Install Flutter dependencies
      run: flutter pub get
    
    - 

    - name: Run tests
      run: make qtest