name: Flutter CI

on:
  push:
    branches:
      - dev

jobs:

  build-release-upload-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Confirm the branch
        run: git status
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64
          flutter-version: 3.22.2
      - run: flutter --version
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y clang cmake pkg-config libgtk-3-0 libblkid1 liblzma5
      - name: Build package
        run: flutter build linux --release
      - name: Zip the bundle
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Upload the zip bundle to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rattle-linux
          path: build/linux/x64/release/bundle/rattle-${{github.ref_name}}-linux.zip
      - name: Linux Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/linux/x64/release/bundle/rattle-${{github.ref_name}}-linux.zip

  build-release-upload-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.22.2'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Windows Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/rattle-${{github.ref_name}}-windows.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rattle-windows
          path: build/windows/x64/runner/Release/rattle-${{github.ref_name}}-windows.zip

  build-release-upload-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.22.2'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: rattle-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release
      - run: ls -laRsh
      - name: macOS Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/rattle-${{github.ref_name}}-macos.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rattle-macos
          path: build/macos/Build/Products/Release/rattle-${{github.ref_name}}-macos.zip
